language: php
php:
  - 5.4

script: phpunit --bootstrap tests/travis.php tests/unit/ --coverage-clover build/logs/clover.xml

addons:
  code_climate:
    repo_token: 13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360

after_script:
  - vendor/bin/test-reporter